// lcg_xor.h - LCG-XOR stream cipher for encrypted-name API resolver.
//
// Per-byte keystream: 32-bit state advanced by the Knuth golden-ratio constant
// each iteration, mixed via glibc rand() LCG (0x41C64E6D * x + 0x3039),
// xorshift diffusion, final byte extracted by multiply-and-mix.
//
// Self-inverse: apply twice with same key -> original. One function handles
// both encrypt and decrypt.
//
// Single-header, C-compatible so the kerneldriver .c file can include it
// alongside user-mode C++ tools.
//
// Uses `unsigned int` (required to be at least 32-bit on any target we
// compile for — x64 MSVC is exactly 32-bit) and `unsigned char` rather than
// stdint types, so both kernel (ntddk.h) and user-mode (windows.h) builds
// compile clean without dragging in WDK-incompatible vcruntime headers.

#pragma once

#include <stddef.h>  // size_t

#ifdef __cplusplus
extern "C" {
#endif

static __inline void lcg_xor_apply(unsigned char* buf, size_t len, unsigned int key_const) {
    unsigned int state = 0;
    for (size_t i = 0; i < len; ++i) {
        unsigned int prev = state;
        state = state - 0x61C88647u;
        unsigned int mix = 0x41C64E6Du * (prev ^ key_const) + 0x3039u;
        mix ^= mix >> 16;
        unsigned char keybyte = (unsigned char)((59u * mix) ^ ((0x045D9F3Bu * mix) >> 16));
        buf[i] ^= keybyte;
    }
}

// LCG-XOR-wide (spec §4.2): operates on 16-bit WORDs. Two bytes per wchar
// generated by two inner iterations (low byte at shift 0, high byte at shift 8).
// `state` is a single running u32 counter, incremented once per inner pass.
// Self-inverse: apply twice with same key -> original wide string.
static __inline void lcg_xor_apply_wide(unsigned short* buf, size_t wchar_count, unsigned int key_const) {
    unsigned int state = 0;
    for (size_t i = 0; i < wchar_count; ++i) {
        unsigned short word_key = 0;
        int inner_shift;
        for (inner_shift = 0; inner_shift <= 8; inner_shift += 8) {
            unsigned int mul = 0x61C88647u * state;
            ++state;
            unsigned int mix = 0x41C64E6Du * ((0x3C6EF35Fu * (unsigned int)i - mul) ^ key_const) + 0x3039u;
            mix ^= mix >> 16;
            unsigned char byte = (unsigned char)((mix ^ (mix >> 16)) & 0xFFu);
            word_key = (unsigned short)(word_key | ((unsigned short)byte << inner_shift));
        }
        buf[i] ^= word_key;
    }
}

#ifdef __cplusplus
}
#endif
