// phase14_encrypted_names.h - AUTO-GENERATED by lcg_xor_test. Do not edit.
//
// Encrypted ASCII name blobs for Phase 14 API resolver (19 entries).
// Each blob = `name + '\0'` run through lcg_xor_apply with key = FNV-1a(name).
// Driver decrypts at DriverEntry and feeds the result to the export walker.

#pragma once

// [0] "PsLookupProcessByProcessId" (len 27 incl. null), key 0x2E6C03B2
static const unsigned char enc_name_PsLookupProcessByProcessId[27] = {
    0xC3, 0xCF, 0x8F, 0xDA, 0x76, 0x35, 0x4D, 0x12, 
    0x31, 0x39, 0xD1, 0x56, 0xC2, 0xD0, 0xC7, 0x02, 
    0x6F, 0x73, 0xFC, 0xC1, 0x50, 0x9D, 0xBA, 0x09, 
    0x39, 0x78, 0xC4, 
};
#define KEY_enc_name_PsLookupProcessByProcessId 0x2E6C03B2u
#define LEN_enc_name_PsLookupProcessByProcessId 27u

// [1] "MmIsAddressValid" (len 17 incl. null), key 0x086D022D
static const unsigned char enc_name_MmIsAddressValid[17] = {
    0x0A, 0x3C, 0xC9, 0x68, 0xA2, 0x37, 0x8F, 0x15, 
    0x5E, 0x87, 0x66, 0x60, 0xE6, 0x30, 0x18, 0xF7, 
    0xD3, 
};
#define KEY_enc_name_MmIsAddressValid 0x086D022Du
#define LEN_enc_name_MmIsAddressValid 17u

// [2] "PsGetProcessExitStatus" (len 23 incl. null), key 0xBA080AF7
static const unsigned char enc_name_PsGetProcessExitStatus[23] = {
    0x12, 0x0B, 0xE5, 0x36, 0x4F, 0x0B, 0x0E, 0x2C, 
    0x7C, 0xE9, 0x98, 0xC2, 0x05, 0xA8, 0xB6, 0x1A, 
    0xC1, 0x2A, 0x12, 0x7C, 0x30, 0xF5, 0x8A, 
};
#define KEY_enc_name_PsGetProcessExitStatus 0xBA080AF7u
#define LEN_enc_name_PsGetProcessExitStatus 23u

// [3] "ObfDereferenceObject" (len 21 incl. null), key 0x5BC54B45
static const unsigned char enc_name_ObfDereferenceObject[21] = {
    0x28, 0xAE, 0x72, 0xB7, 0xFF, 0xFB, 0x64, 0x3A, 
    0x91, 0x8C, 0xFD, 0x92, 0x8A, 0xCE, 0x54, 0xF1, 
    0x82, 0xC1, 0xDE, 0x19, 0xA1, 
};
#define KEY_enc_name_ObfDereferenceObject 0x5BC54B45u
#define LEN_enc_name_ObfDereferenceObject 21u

// [4] "PsGetProcessPeb" (len 16 incl. null), key 0x5D5EE8AC
static const unsigned char enc_name_PsGetProcessPeb[16] = {
    0x2B, 0xF9, 0xDE, 0xC6, 0x07, 0x0C, 0x4E, 0x72, 
    0x68, 0x6B, 0xFA, 0x88, 0x09, 0xF6, 0x78, 0x58, 
};
#define KEY_enc_name_PsGetProcessPeb 0x5D5EE8ACu
#define LEN_enc_name_PsGetProcessPeb 16u

// [5] "KeDelayExecutionThread" (len 23 incl. null), key 0x97096872
static const unsigned char enc_name_KeDelayExecutionThread[23] = {
    0x71, 0x33, 0xAB, 0xFE, 0x4B, 0x34, 0x75, 0xD8, 
    0x1F, 0x7D, 0x07, 0x4A, 0x73, 0x96, 0x5A, 0x86, 
    0x53, 0xFF, 0xFE, 0xD4, 0x7E, 0x36, 0x1E, 
};
#define KEY_enc_name_KeDelayExecutionThread 0x97096872u
#define LEN_enc_name_KeDelayExecutionThread 23u

// [6] "RtlInitUnicodeString" (len 21 incl. null), key 0x3376500F
static const unsigned char enc_name_RtlInitUnicodeString[21] = {
    0xA8, 0x13, 0x4E, 0x79, 0x81, 0xF6, 0xE6, 0x1B, 
    0x50, 0x31, 0xA5, 0xE9, 0x22, 0xAF, 0xDD, 0x94, 
    0x00, 0x34, 0xBE, 0x1E, 0x95, 
};
#define KEY_enc_name_RtlInitUnicodeString 0x3376500Fu
#define LEN_enc_name_RtlInitUnicodeString 21u

// [7] "ZwAllocateVirtualMemory" (len 24 incl. null), key 0x300F94D7
static const unsigned char enc_name_ZwAllocateVirtualMemory[24] = {
    0x80, 0x08, 0x4E, 0x6E, 0xCC, 0x79, 0xB3, 0x74, 
    0x4B, 0x2C, 0x18, 0x8F, 0x06, 0x0E, 0x13, 0x77, 
    0x01, 0xB1, 0xD7, 0xB1, 0x37, 0xBE, 0x58, 0x24, 
};
#define KEY_enc_name_ZwAllocateVirtualMemory 0x300F94D7u
#define LEN_enc_name_ZwAllocateVirtualMemory 24u

// [8] "ZwFreeVirtualMemory" (len 20 incl. null), key 0x70AAB4F8
static const unsigned char enc_name_ZwFreeVirtualMemory[20] = {
    0xDC, 0xA5, 0x8E, 0xF9, 0x4D, 0xE5, 0xD4, 0x67, 
    0x5E, 0x9B, 0x98, 0x29, 0x4F, 0xDA, 0x3F, 0x1C, 
    0x22, 0x2F, 0x79, 0xD3, 
};
#define KEY_enc_name_ZwFreeVirtualMemory 0x70AAB4F8u
#define LEN_enc_name_ZwFreeVirtualMemory 20u

// [9] "ZwProtectVirtualMemory" (len 23 incl. null), key 0x29B2C23F
static const unsigned char enc_name_ZwProtectVirtualMemory[23] = {
    0x8A, 0xA9, 0xCA, 0x02, 0x7C, 0xE1, 0x6E, 0x51, 
    0x42, 0x81, 0xEF, 0xC1, 0xF6, 0xE2, 0x6F, 0x9E, 
    0x7B, 0x36, 0xD4, 0x55, 0xBA, 0x1B, 0x8B, 
};
#define KEY_enc_name_ZwProtectVirtualMemory 0x29B2C23Fu
#define LEN_enc_name_ZwProtectVirtualMemory 23u

// [10] "ZwQueryVirtualMemory" (len 21 incl. null), key 0x192EBA62
static const unsigned char enc_name_ZwQueryVirtualMemory[21] = {
    0xA2, 0xD1, 0x24, 0x33, 0x8B, 0xF0, 0x73, 0x93, 
    0xE6, 0xCD, 0x47, 0x8F, 0x92, 0x4D, 0x3B, 0x09, 
    0xD3, 0x7B, 0xFA, 0x3B, 0x59, 
};
#define KEY_enc_name_ZwQueryVirtualMemory 0x192EBA62u
#define LEN_enc_name_ZwQueryVirtualMemory 21u

// [11] "ExGetPreviousMode" (len 18 incl. null), key 0x2F03D7E6
static const unsigned char enc_name_ExGetPreviousMode[18] = {
    0x1D, 0x0B, 0xDA, 0x6C, 0x70, 0x0F, 0xF7, 0x75, 
    0xE9, 0x9D, 0xB7, 0xE3, 0xF9, 0xF0, 0x52, 0x53, 
    0x80, 0x11, 
};
#define KEY_enc_name_ExGetPreviousMode 0x2F03D7E6u
#define LEN_enc_name_ExGetPreviousMode 18u

// [12] "RtlCompareUnicodeString" (len 24 incl. null), key 0x28BB7FCA
static const unsigned char enc_name_RtlCompareUnicodeString[24] = {
    0x6C, 0xA1, 0x09, 0x38, 0xC1, 0xE7, 0x8C, 0xC9, 
    0x8B, 0xD4, 0x25, 0x1E, 0xEE, 0xB3, 0x3F, 0xFD, 
    0x46, 0x12, 0x5A, 0x26, 0xA9, 0xDD, 0x21, 0x9C, 
};
#define KEY_enc_name_RtlCompareUnicodeString 0x28BB7FCAu
#define LEN_enc_name_RtlCompareUnicodeString 24u

// [13] "ExAllocatePoolWithTag" (len 22 incl. null), key 0xC4A77D9F
static const unsigned char enc_name_ExAllocatePoolWithTag[22] = {
    0x8A, 0x67, 0xED, 0x77, 0xE3, 0xBC, 0xBF, 0xA0, 
    0x0C, 0xD7, 0x9B, 0x55, 0xE1, 0x02, 0xDA, 0xD1, 
    0xD3, 0x66, 0x33, 0x46, 0x39, 0xDE, 
};
#define KEY_enc_name_ExAllocatePoolWithTag 0xC4A77D9Fu
#define LEN_enc_name_ExAllocatePoolWithTag 22u

// [14] "ExFreePoolWithTag" (len 18 incl. null), key 0x95A38B3C
static const unsigned char enc_name_ExFreePoolWithTag[18] = {
    0x7F, 0xE3, 0xD0, 0x71, 0x7C, 0x9E, 0x3C, 0x81, 
    0x74, 0x07, 0x75, 0xD0, 0x43, 0x66, 0xC8, 0x59, 
    0x17, 0x37, 
};
#define KEY_enc_name_ExFreePoolWithTag 0x95A38B3Cu
#define LEN_enc_name_ExFreePoolWithTag 18u

// [15] "IoGetCurrentProcess" (len 20 incl. null), key 0xB57AB5A1
static const unsigned char enc_name_IoGetCurrentProcess[20] = {
    0x6E, 0xC4, 0xEB, 0x27, 0xE7, 0x1A, 0x8D, 0x82, 
    0x11, 0x81, 0xD5, 0x7F, 0xB1, 0xB1, 0x95, 0x55, 
    0x5E, 0xFC, 0xCC, 0x01, 
};
#define KEY_enc_name_IoGetCurrentProcess 0xB57AB5A1u
#define LEN_enc_name_IoGetCurrentProcess 20u

// [16] "KeStackAttachProcess" (len 21 incl. null), key 0xD807DA3F
static const unsigned char enc_name_KeStackAttachProcess[21] = {
    0x6C, 0x1A, 0x02, 0x58, 0xF3, 0x74, 0xC8, 0x7F, 
    0x88, 0xE2, 0x00, 0xA7, 0x08, 0x47, 0x2D, 0x31, 
    0x2C, 0xA8, 0xE8, 0x4A, 0x1F, 
};
#define KEY_enc_name_KeStackAttachProcess 0xD807DA3Fu
#define LEN_enc_name_KeStackAttachProcess 21u

// [17] "KeUnstackDetachProcess" (len 23 incl. null), key 0x5BC2E9AA
static const unsigned char enc_name_KeUnstackDetachProcess[23] = {
    0x26, 0x6A, 0xC1, 0xD6, 0xDB, 0x59, 0xAE, 0xF1, 
    0x27, 0x8B, 0x7B, 0x00, 0xC6, 0x8A, 0xAB, 0x52, 
    0xFA, 0x3D, 0x14, 0x4F, 0x6E, 0x70, 0x13, 
};
#define KEY_enc_name_KeUnstackDetachProcess 0x5BC2E9AAu
#define LEN_enc_name_KeUnstackDetachProcess 23u

// [18] "MmCopyVirtualMemory" (len 20 incl. null), key 0x9232E176
static const unsigned char enc_name_MmCopyVirtualMemory[20] = {
    0x18, 0xA6, 0x16, 0xCD, 0x33, 0x8A, 0xE4, 0xA6, 
    0x9E, 0xCC, 0x53, 0xA1, 0x57, 0x21, 0x62, 0x9E, 
    0x5A, 0x3F, 0xDF, 0x3A, 
};
#define KEY_enc_name_MmCopyVirtualMemory 0x9232E176u
#define LEN_enc_name_MmCopyVirtualMemory 20u

// [19] "MmGetVirtualForPhysical" (len 24 incl. null), key 0x980E4062
static const unsigned char enc_name_MmGetVirtualForPhysical[24] = {
    0x5C, 0x40, 0x72, 0xB8, 0x44, 0xF3, 0x3B, 0x8A, 
    0x3A, 0x18, 0xF1, 0xFF, 0xC3, 0x0F, 0xB3, 0xD6, 
    0x07, 0x99, 0x2C, 0x02, 0xE7, 0x27, 0x4F, 0x09, 
};
#define KEY_enc_name_MmGetVirtualForPhysical 0x980E4062u
#define LEN_enc_name_MmGetVirtualForPhysical 24u

enum phase14_api_slot {
    API_PsLookupProcessByProcessId = 0,
    API_MmIsAddressValid = 1,
    API_PsGetProcessExitStatus = 2,
    API_ObfDereferenceObject = 3,
    API_PsGetProcessPeb = 4,
    API_KeDelayExecutionThread = 5,
    API_RtlInitUnicodeString = 6,
    API_ZwAllocateVirtualMemory = 7,
    API_ZwFreeVirtualMemory = 8,
    API_ZwProtectVirtualMemory = 9,
    API_ZwQueryVirtualMemory = 10,
    API_ExGetPreviousMode = 11,
    API_RtlCompareUnicodeString = 12,
    API_ExAllocatePoolWithTag = 13,
    API_ExFreePoolWithTag = 14,
    API_IoGetCurrentProcess = 15,
    API_KeStackAttachProcess = 16,
    API_KeUnstackDetachProcess = 17,
    API_MmCopyVirtualMemory = 18,
    API_MmGetVirtualForPhysical = 19,
    API_COUNT = 20
};

typedef struct phase14_api_entry {
    const unsigned char* blob;
    unsigned int         len;
    unsigned int         key;
} phase14_api_entry_t;

static const phase14_api_entry_t g_encrypted_apis[API_COUNT] = {
    { enc_name_PsLookupProcessByProcessId, LEN_enc_name_PsLookupProcessByProcessId, KEY_enc_name_PsLookupProcessByProcessId },
    { enc_name_MmIsAddressValid, LEN_enc_name_MmIsAddressValid, KEY_enc_name_MmIsAddressValid },
    { enc_name_PsGetProcessExitStatus, LEN_enc_name_PsGetProcessExitStatus, KEY_enc_name_PsGetProcessExitStatus },
    { enc_name_ObfDereferenceObject, LEN_enc_name_ObfDereferenceObject, KEY_enc_name_ObfDereferenceObject },
    { enc_name_PsGetProcessPeb, LEN_enc_name_PsGetProcessPeb, KEY_enc_name_PsGetProcessPeb },
    { enc_name_KeDelayExecutionThread, LEN_enc_name_KeDelayExecutionThread, KEY_enc_name_KeDelayExecutionThread },
    { enc_name_RtlInitUnicodeString, LEN_enc_name_RtlInitUnicodeString, KEY_enc_name_RtlInitUnicodeString },
    { enc_name_ZwAllocateVirtualMemory, LEN_enc_name_ZwAllocateVirtualMemory, KEY_enc_name_ZwAllocateVirtualMemory },
    { enc_name_ZwFreeVirtualMemory, LEN_enc_name_ZwFreeVirtualMemory, KEY_enc_name_ZwFreeVirtualMemory },
    { enc_name_ZwProtectVirtualMemory, LEN_enc_name_ZwProtectVirtualMemory, KEY_enc_name_ZwProtectVirtualMemory },
    { enc_name_ZwQueryVirtualMemory, LEN_enc_name_ZwQueryVirtualMemory, KEY_enc_name_ZwQueryVirtualMemory },
    { enc_name_ExGetPreviousMode, LEN_enc_name_ExGetPreviousMode, KEY_enc_name_ExGetPreviousMode },
    { enc_name_RtlCompareUnicodeString, LEN_enc_name_RtlCompareUnicodeString, KEY_enc_name_RtlCompareUnicodeString },
    { enc_name_ExAllocatePoolWithTag, LEN_enc_name_ExAllocatePoolWithTag, KEY_enc_name_ExAllocatePoolWithTag },
    { enc_name_ExFreePoolWithTag, LEN_enc_name_ExFreePoolWithTag, KEY_enc_name_ExFreePoolWithTag },
    { enc_name_IoGetCurrentProcess, LEN_enc_name_IoGetCurrentProcess, KEY_enc_name_IoGetCurrentProcess },
    { enc_name_KeStackAttachProcess, LEN_enc_name_KeStackAttachProcess, KEY_enc_name_KeStackAttachProcess },
    { enc_name_KeUnstackDetachProcess, LEN_enc_name_KeUnstackDetachProcess, KEY_enc_name_KeUnstackDetachProcess },
    { enc_name_MmCopyVirtualMemory, LEN_enc_name_MmCopyVirtualMemory, KEY_enc_name_MmCopyVirtualMemory },
    { enc_name_MmGetVirtualForPhysical, LEN_enc_name_MmGetVirtualForPhysical, KEY_enc_name_MmGetVirtualForPhysical },
};

// Wide-char "ntoskrnl.exe" (13 wchars incl. null = 26 bytes), key 0x5A0275D2
// Decrypt with lcg_xor_apply_wide(buf, 13, KEY_enc_ntoskrnl_wide).
static const unsigned char enc_ntoskrnl_wide[26] = {
    0xCD, 0xC8, 0xF4, 0xB1, 0x86, 0x8E, 0xB5, 0x5F, 
    0x7C, 0x3C, 0x86, 0x25, 0x33, 0x02, 0x56, 0x33, 
    0xA5, 0xD0, 0x0D, 0xF9, 0xA9, 0x16, 0xCB, 0xA7, 
    0xFF, 0x44, 
};
#define KEY_enc_ntoskrnl_wide 0x5A0275D2u
#define LEN_enc_ntoskrnl_wide_wchars 13u
